import type { Job } from '../types/job';

export const DIRECT_ATS_ENGINEERING_JOBS: Job[] = [
  {
    id: 'direct-asml-mech-01',
    title: 'Mechanical Design Engineer - EUV Lithography Modules',
    company: 'ASML',
    companyLogo: 'https://avatar.vercel.sh/asml.svg?text=AS',
    rating: 4.8,
    reviewsCount: 1420,
    isSuperEmployer: true,
    isFeatured: true,
    category: 'Engineering',
    location: 'Veldhoven, Eindhoven (NL)',
    address: 'De Run 6501, 5504 DR Veldhoven',
    city: 'eindhoven',
    lat: 51.4052,
    lng: 5.4180,
    salaryMin: 68000,
    salaryMax: 88000,
    salaryCurrency: '€',
    salaryPeriod: 'year',
    salaryDisplay: '€68k - €88k',
    salaryBadge: '€78k',
    jobType: 'Full-time',
    remoteType: 'Hybrid',
    experienceLevel: 'Mid',
    visaSponsorship: true,
    images: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=1000&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=1000&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1000&auto=format&fit=crop&q=85',
    ],
    description: 'Design precision mechanical components and structural assemblies for ASML state-of-the-art EUV lithography machines. Interface with mechatronics, thermal dynamics, and optical engineering teams.',
    responsibilities: [
      'Perform 3D CAD modeling and FEM structural simulations using NX and Ansys',
      'Analyze thermal expansion, mechanical tolerances, and micro-vibration behavior',
      'Collaborate with cleanroom manufacturing teams on precision integration'
    ],
    requirements: [
      'Master or Bachelor in Mechanical Engineering, Mechatronics, or related discipline',
      'Proficiency in 3D CAD (Siemens NX, CATIA, or SolidWorks) and FEA',
      'Fluent English; strong problem-solving mindset'
    ],
    benefits: [
      'Full relocation assistance & 30% ruling tax facility support',
      'Generous pension, 40 vacation days, annual bonus'
    ],
    postedDaysAgo: 1,
    postedAt: '1 day ago',
    applicantCount: 14,
    applyUrl: 'https://asml.wd3.myworkdayjobs.com/en-US/ASML_Careers/job/Mechanical-Design-Engineer_JR10923',
    atsProvider: 'Workday',
    isDirectApply: true,
  },
  {
    id: 'direct-philips-mech-02',
    title: 'Precision Mechanical Engineer - Image-Guided Therapy',
    company: 'Philips',
    companyLogo: 'https://avatar.vercel.sh/philips.svg?text=PH',
    rating: 4.5,
    reviewsCount: 980,
    isSuperEmployer: true,
    isFeatured: true,
    category: 'Engineering',
    location: 'Best, Eindhoven Tech Campus (NL)',
    address: 'Veenpluis 4-6, 5684 PC Best',
    city: 'eindhoven',
    lat: 51.5020,
    lng: 5.4050,
    salaryMin: 62000,
    salaryMax: 79000,
    salaryCurrency: '€',
    salaryPeriod: 'year',
    salaryDisplay: '€62k - €79k',
    salaryBadge: '€70k',
    jobType: 'Full-time',
    remoteType: 'Hybrid',
    experienceLevel: 'Mid',
    visaSponsorship: true,
    images: [
      'https://images.unsplash.com/photo-1581092162384-8987c1d64718?w=1000&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1000&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1581092334651-ddf26d9a09d0?w=1000&auto=format&fit=crop&q=85',
    ],
    description: 'Design and develop complex mechanical medical device mechanisms for cardiovascular X-ray systems. Ensure high structural reliability and strict compliance with medical standards.',
    responsibilities: [
      'Develop robotic articulation structures and precision counterweight mechanisms',
      'Conduct fatigue life calculations and safety margin verifications',
      'Participate in rapid prototyping and prototype testing at Best Innovation Center'
    ],
    requirements: [
      'Degree in Mechanical Engineering with 2+ years design experience',
      'Solid knowledge of mechanics of materials and geometric dimensioning (GD&T)',
      'Experience with medical devices (ISO 13485) is a plus'
    ],
    benefits: [
      'Competitive salary + 25 vacation days + 15 collective days',
      'High Tech Campus access, Dutch language course funding'
    ],
    postedDaysAgo: 2,
    postedAt: '2 days ago',
    applicantCount: 9,
    applyUrl: 'https://philips.wd3.myworkdayjobs.com/en-US/jobs-and-careers/job/Mechanical-Engineer_49124',
    atsProvider: 'Workday',
    isDirectApply: true,
  },
  {
    id: 'direct-safran-mech-03',
    title: 'Ingenieur Conception Mecanique Turbomachines',
    company: 'Safran',
    companyLogo: 'https://avatar.vercel.sh/safran.svg?text=SA',
    rating: 4.7,
    reviewsCount: 1850,
    isSuperEmployer: true,
    isFeatured: true,
    category: 'Engineering',
    location: 'Saclay, Paris R&D Hub (FR)',
    address: 'Rue Henri Auguste Pelegrin, 91190 Gif-sur-Yvette',
    city: 'paris',
    lat: 48.7110,
    lng: 2.1620,
    salaryMin: 55000,
    salaryMax: 72000,
    salaryCurrency: '€',
    salaryPeriod: 'year',
    salaryDisplay: '€55k - €72k',
    salaryBadge: '€64k',
    jobType: 'Full-time',
    remoteType: 'Hybrid',
    experienceLevel: 'Mid',
    visaSponsorship: true,
    images: [
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1000&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1000&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1000&auto=format&fit=crop&q=85',
    ],
    description: 'Au sein du departement bureau d etudes propulsion, vous assurez la conception mecanique et le dimensionnement de sous-ensembles pour moteurs aeronautiques de nouvelle generation.',
    responsibilities: [
      'Conception 3D sous CATIA V5 / 3DEXPERIENCE des composants aubages et carters',
      'Calculs mecaniques de tenue structurale et thermique en regime dynamique',
      'Echanges techniques avec la production et les essais bancs moteur'
    ],
    requirements: [
      'Diplome d Ingenieur en Genie Mecanique / Aeronautique',
      'Maitrise de CATIA V5 et des bases de dimensionnement par elements finis (FEM)',
      'Rigueur, autonomie et gout pour les systemes mecaniques complexes'
    ],
    benefits: [
      'Accord teletravail jusqu a 2 jours / semaine',
      'Interessement / Participation avantageux, mutuelle haut de gamme'
    ],
    postedDaysAgo: 1,
    postedAt: '1 day ago',
    applicantCount: 18,
    applyUrl: 'https://safran.wd3.myworkdayjobs.com/fr-FR/Safran_Careers/job/Ingenieur-Conception-Mecanique_R02194',
    atsProvider: 'Workday',
    isDirectApply: true,
  },
  {
    id: 'direct-palantir-lever-04',
    title: 'Forward Deployed Engineering - Industrial Systems',
    company: 'Palantir',
    companyLogo: 'https://avatar.vercel.sh/palantir.svg?text=PL',
    rating: 4.6,
    reviewsCount: 650,
    isSuperEmployer: true,
    isFeatured: true,
    category: 'Engineering',
    location: 'Paris, 8e Arrondissement (FR)',
    address: 'Rue de la Boetie, 75008 Paris',
    city: 'paris',
    lat: 48.8740,
    lng: 2.3130,
    salaryMin: 90000,
    salaryMax: 125000,
    salaryCurrency: '€',
    salaryPeriod: 'year',
    salaryDisplay: '€90k - €125k',
    salaryBadge: '€105k',
    jobType: 'Full-time',
    remoteType: 'Hybrid',
    experienceLevel: 'Mid',
    visaSponsorship: true,
    images: [
      'https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?w=1000&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=1000&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=1000&auto=format&fit=crop&q=85',
    ],
    description: 'Work directly on-site with aerospace and industrial manufacturers to integrate high-velocity engineering telemetry, predictive maintenance, and supply-chain digital twins.',
    responsibilities: [
      'Deploy complex operational workflows integrating CAD, IoT sensors, and ERP feeds',
      'Build analytical models mapping assembly line tolerances and part lifecycles',
      'Partner with senior client engineering executives to unlock operational throughput'
    ],
    requirements: [
      'Engineering degree (Mechanical, Aerospace, Industrial, or Computer Science)',
      'Strong analytical rigor and comfort with quantitative data and scripting',
      'Excellent bilingual communication in French and English'
    ],
    benefits: [
      'Significant equity grant (RSUs)',
      'Premium health insurance, comprehensive mental wellness stipend'
    ],
    postedDaysAgo: 3,
    postedAt: '3 days ago',
    applicantCount: 22,
    applyUrl: 'https://jobs.lever.co/palantir/67dfa812-4012-48ea-8b01-engineering-paris',
    atsProvider: 'Lever',
    isDirectApply: true,
  },
  {
    id: 'direct-mistral-ashby-05',
    title: 'Hardware & AI Cluster Systems Engineer',
    company: 'Mistral AI',
    companyLogo: 'https://avatar.vercel.sh/mistral.svg?text=MI',
    rating: 4.9,
    reviewsCount: 310,
    isSuperEmployer: true,
    isFeatured: true,
    category: 'Engineering',
    location: 'Paris, Sentier / Tech Quarter (FR)',
    address: 'Rue de Clery, 75002 Paris',
    city: 'paris',
    lat: 48.8685,
    lng: 2.3470,
    salaryMin: 95000,
    salaryMax: 140000,
    salaryCurrency: '€',
    salaryPeriod: 'year',
    salaryDisplay: '€95k - €140k',
    salaryBadge: '€115k',
    jobType: 'Full-time',
    remoteType: 'Hybrid',
    experienceLevel: 'Senior',
    visaSponsorship: true,
    images: [
      'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=1000&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1000&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1000&auto=format&fit=crop&q=85',
    ],
    description: 'Lead thermal management, power distribution design, and physical rack architecture for high-density liquid-cooled GPU supercomputing infrastructure.',
    responsibilities: [
      'Optimize liquid cooling loops, manifold CFD calculations, and heat exchange systems',
      'Validate physical chassis designs against mechanical shock and acoustic vibrations',
      'Coordinate with European datacenter facilities on high-voltage power integration'
    ],
    requirements: [
      'Degree in Mechanical, Thermal, or Systems Engineering',
      'Experience in thermal dissipation or liquid cooling for electronics/datacenter racks',
      'Proactive team player in high-growth startup environment'
    ],
    benefits: [
      'Competitive base salary + early-stage Mistral AI stock equity',
      'Top-tier medical coverage, daily catered lunch in central Paris'
    ],
    postedDaysAgo: 2,
    postedAt: '2 days ago',
    applicantCount: 35,
    applyUrl: 'https://jobs.ashbyhq.com/mistral/hardware-systems-engineer-paris',
    atsProvider: 'Ashby',
    isDirectApply: true,
  },
  {
    id: 'direct-airbus-mech-06',
    title: 'Structural Design Engineer - Next-Gen Composite Wings',
    company: 'Airbus',
    companyLogo: 'https://avatar.vercel.sh/airbus.svg?text=AB',
    rating: 4.7,
    reviewsCount: 3200,
    isSuperEmployer: true,
    isFeatured: true,
    category: 'Engineering',
    location: 'Blagnac, Toulouse Aerospace Hub (FR)',
    address: 'Rond-Point Emile Dewoitine, 31700 Blagnac',
    city: 'toulouse',
    lat: 43.6290,
    lng: 1.3720,
    salaryMin: 52000,
    salaryMax: 70000,
    salaryCurrency: '€',
    salaryPeriod: 'year',
    salaryDisplay: '€52k - €70k',
    salaryBadge: '€60k',
    jobType: 'Full-time',
    remoteType: 'Hybrid',
    experienceLevel: 'Mid',
    visaSponsorship: true,
    images: [
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1000&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1000&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1581092162384-8987c1d64718?w=1000&auto=format&fit=crop&q=85',
    ],
    description: 'Design and validate primary composite structures for commercial airliner wing architectures. Conduct finite element calculations, fatigue analyses, and damage tolerance verifications.',
    responsibilities: [
      'Create 3D master CAD models of composite ribs, stringers, and skin panels in CATIA V5',
      'Perform linear and non-linear stress analyses using Nastran/Patran',
      'Support flight certification documentation with EASA / FAA requirements'
    ],
    requirements: [
      'Degree in Mechanical, Aeronautical, or Materials Engineering',
      'Solid experience in composite materials mechanics and laminate design',
      'Familiarity with aerospace stress standards'
    ],
    benefits: [
      'World-class aeronautical aerospace campus in Toulouse',
      'Airbus profit-sharing and European relocation assistance'
    ],
    postedDaysAgo: 1,
    postedAt: '1 day ago',
    applicantCount: 27,
    applyUrl: 'https://airbus.wd3.myworkdayjobs.com/fr-FR/Airbus_Careers/job/Structural-Design-Engineer_JR100482',
    atsProvider: 'Workday',
    isDirectApply: true,
  },
  {
    id: 'direct-siemens-mech-07',
    title: 'Mechanical Simulation Engineer (CAD/CAE)',
    company: 'Siemens',
    companyLogo: 'https://avatar.vercel.sh/siemens.svg?text=SI',
    rating: 4.6,
    reviewsCount: 2700,
    isSuperEmployer: true,
    isFeatured: true,
    category: 'Engineering',
    location: 'Munich, Garching Tech Campus (DE)',
    address: 'Werner-von-Siemens-Strasse 1, 80333 Munchen',
    city: 'munich',
    lat: 48.1450,
    lng: 11.5720,
    salaryMin: 68000,
    salaryMax: 89000,
    salaryCurrency: '€',
    salaryPeriod: 'year',
    salaryDisplay: '€68k - €89k',
    salaryBadge: '€78k',
    jobType: 'Full-time',
    remoteType: 'Hybrid',
    experienceLevel: 'Mid',
    visaSponsorship: true,
    images: [
      'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1000&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1581092334651-ddf26d9a09d0?w=1000&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?w=1000&auto=format&fit=crop&q=85',
    ],
    description: 'Perform multidisciplinary mechanical simulations (FEA, Multibody Dynamics, Thermal) for industrial machinery and electrification drivetrains.',
    responsibilities: [
      'Simulate structural durability, modal analysis, and vibration acoustics using Simcenter 3D',
      'Optimize weight and topology using generative design algorithms',
      'Interface with international testing laboratories to validate numerical models'
    ],
    requirements: [
      'Master in Mechanical Engineering (Maschinenbau) or Computational Mechanics',
      'Solid hands-on skills in Simcenter, Ansys, or Abaqus',
      'English proficiency required; German is advantageous'
    ],
    benefits: [
      'IG Metall tariff contract with 35-hour work week',
      'Munich public transit ticket, subsidized company canteen'
    ],
    postedDaysAgo: 2,
    postedAt: '2 days ago',
    applicantCount: 16,
    applyUrl: 'https://jobs.siemens.com/jobs/mechanical-simulation-engineer-munich',
    atsProvider: 'Workday',
    isDirectApply: true,
  },
  {
    id: 'direct-stripe-greenhouse-08',
    title: 'Integration Systems Solutions Engineer',
    company: 'Stripe',
    companyLogo: 'https://avatar.vercel.sh/stripe.svg?text=ST',
    rating: 4.8,
    reviewsCount: 780,
    isSuperEmployer: true,
    isFeatured: true,
    category: 'Engineering',
    location: 'Amsterdam, Zuidas Financial Center (NL)',
    address: 'Gustav Mahlerplein 2, 1082 MA Amsterdam',
    city: 'amsterdam',
    lat: 52.3360,
    lng: 4.8720,
    salaryMin: 85000,
    salaryMax: 115000,
    salaryCurrency: '€',
    salaryPeriod: 'year',
    salaryDisplay: '€85k - €115k',
    salaryBadge: '€100k',
    jobType: 'Full-time',
    remoteType: 'Hybrid',
    experienceLevel: 'Mid',
    visaSponsorship: true,
    images: [
      'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=1000&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=1000&auto=format&fit=crop&q=85',
      'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=1000&auto=format&fit=crop&q=85',
    ],
    description: 'Work with major European engineering & industrial tech enterprises integrating Stripe global payment automation and hardware terminal architectures.',
    responsibilities: [
      'Architect robust integration pipelines for high-volume enterprise users',
      'Debug cross-platform SDK and physical POS hardware communications',
      'Serve as trusted technical advisor on system reliability and fraud mitigation'
    ],
    requirements: [
      'Engineering degree with strong programming and systems design foundations',
      'Experience in technical consulting or solutions architecture',
      'Strong interpersonal and analytical communication skills'
    ],
    benefits: [
      'Generous equity package, full relocation support for the Netherlands',
      'Health insurance, commuter allowance, Dutch 30% tax ruling assistance'
    ],
    postedDaysAgo: 1,
    postedAt: '1 day ago',
    applicantCount: 19,
    applyUrl: 'https://boards.greenhouse.io/stripe/jobs/5912401-integration-solutions-engineer',
    atsProvider: 'Greenhouse',
    isDirectApply: true,
  }
];

export function getDirectAtsJobs(cityId?: string): Job[] {
  if (!cityId || cityId === 'all') {
    return DIRECT_ATS_ENGINEERING_JOBS;
  }
  const c = cityId.toLowerCase();
  const matched = DIRECT_ATS_ENGINEERING_JOBS.filter(
    (j) => j.city.includes(c) || j.location.toLowerCase().includes(c)
  );
  return matched.length > 0 ? matched : DIRECT_ATS_ENGINEERING_JOBS;
}
