import { useCallback, useEffect, useMemo, useState } from 'react';
import { FileText, Loader2, RefreshCw, Sparkles, ExternalLink, Search } from 'lucide-react';
import type { Job } from '../types/job';
import {
  documentUrl, fetchDocuments, tailorJob,
  type TailoredDocument,
} from '../services/tailorApi';

/**
 * The tailoring side of the page.
 *
 * Applying used to attach the same PDF to everything. Here a listing is chosen
 * on the left and gets its own CV and letter on the right, cut from the master
 * against what that employer actually wrote. Nothing is generated by opening
 * this: tailoring costs a model call and twenty seconds, so it happens when
 * asked for, and the same advert asked for twice returns the same document
 * rather than a second, different one.
 *
 * What the model was not allowed to do is shown, not hidden. If it tried to
 * invent a number or a tool, the line under the preview says which, and says
 * that the master's own wording went in instead.
 */

interface TailorPaneProps {
  jobs: Job[];
  /** Jobs already applied to, so the list can say which still need documents. */
  appliedJobIds: Set<string>;
  onOpenJob?: (job: Job) => void;
}

interface Candidate {
  job_id: string;
  title: string;
  company: string;
  location: string;
  url: string;
  description: string;
  job?: Job;
  doc?: TailoredDocument;
}

const PANEL = 'ic-panel rounded-[20px] bg-[rgba(16,18,22,0.72)] backdrop-blur-2xl';

function when(doc?: TailoredDocument): string {
  if (!doc?.created_at) return '';
  const date = new Date(doc.created_at);
  if (Number.isNaN(date.getTime())) return doc.created_at;
  const days = Math.floor((Date.now() - date.getTime()) / 86400000);
  if (days === 0) return 'Today';
  if (days === 1) return 'Yesterday';
  if (days < 7) return `${days} days ago`;
  return date.toLocaleDateString();
}

export function TailorPane({ jobs, appliedJobIds, onOpenJob }: TailorPaneProps) {
  const [docs, setDocs] = useState<TailoredDocument[]>([]);
  const [selected, setSelected] = useState<string>('');
  const [busy, setBusy] = useState<string>('');
  const [error, setError] = useState<string>('');
  const [kind, setKind] = useState<'cv' | 'letter'>('cv');
  const [query, setQuery] = useState('');

  const load = useCallback(async () => {
    try {
      setDocs(await fetchDocuments());
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Could not read the documents folder.');
    }
  }, []);

  useEffect(() => { void load(); }, [load]);

  /**
   * What can be tailored: everything in the current results, plus everything
   * already tailored in an earlier session. The second half matters -- the
   * document outlives the search that produced it, and it has to stay reachable
   * after the results have moved on.
   */
  const candidates = useMemo<Candidate[]>(() => {
    const byId = new Map<string, TailoredDocument>();
    docs.forEach((d) => byId.set(d.job_id, d));
    const seen = new Set<string>();
    const list: Candidate[] = [];
    jobs.forEach((job) => {
      seen.add(job.id);
      list.push({
        job_id: job.id,
        title: job.title,
        company: job.company,
        location: job.location || job.city || '',
        url: job.applyUrl || '',
        description: [job.description, ...(job.requirements || []), ...(job.responsibilities || [])]
          .filter(Boolean).join('\n'),
        job,
        doc: byId.get(job.id),
      });
    });
    docs.forEach((doc) => {
      if (seen.has(doc.job_id)) return;
      list.push({
        job_id: doc.job_id,
        title: doc.title || doc.job_id,
        company: doc.company || '',
        location: doc.location || '',
        url: doc.url || '',
        description: '',
        doc,
      });
    });
    const needle = query.trim().toLowerCase();
    return needle
      ? list.filter((c) => `${c.title} ${c.company} ${c.location}`.toLowerCase().includes(needle))
      : list;
  }, [jobs, docs, query]);

  const current = candidates.find((c) => c.job_id === selected) || candidates[0];
  const doc = current?.doc;

  const run = async (candidate: Candidate, force: boolean) => {
    setBusy(candidate.job_id);
    setError('');
    try {
      const meta = await tailorJob({
        job_id: candidate.job_id,
        title: candidate.title,
        company: candidate.company,
        location: candidate.location,
        url: candidate.url,
        description: candidate.description,
        force,
      });
      setDocs((prev) => [meta, ...prev.filter((d) => d.job_id !== meta.job_id)]);
      setSelected(meta.job_id);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Tailoring failed.');
    } finally {
      setBusy('');
    }
  };

  // The PDF, because that is the artefact. The HTML it was printed from stands
  // in only for a browser that downloads PDFs instead of showing them -- there,
  // the frame would be white and a file would appear in Downloads unasked.
  const pdfUrl = documentUrl(kind === 'cv' ? doc?.files?.cv_pdf : doc?.files?.letter_pdf);
  const htmlUrl = documentUrl(kind === 'cv' ? doc?.files?.cv_html : doc?.files?.letter_html);
  const previewUrl = htmlUrl || pdfUrl || '';

  const invented = doc?.report?.invented || [];
  const reverted = doc?.report?.reverted || [];
  const offLanguage = doc?.report?.off_language || [];
  const offVoice = doc?.report?.off_voice || [];

  return (
    <div className="h-full w-full flex gap-3 min-h-0">

      {/* THE LIST. Same width as the results island, so switching along the
        * rail does not move everything sideways. */}
      <div className={`${PANEL} w-full md:w-[380px] xl:w-[420px] shrink-0 flex flex-col min-h-0 overflow-hidden`}>
        <div className="shrink-0 px-3.5 pt-3 pb-2.5 border-b border-white/[0.09]">
          <div className="flex items-baseline justify-between gap-2">
            <h2 className="text-[15px] font-medium text-[#f5f5f7]">Tailoring</h2>
            <span className="text-[11px] text-[rgba(235,235,245,0.45)]">
              {docs.length} prepared
            </span>
          </div>
          <div className="mt-2 flex items-center gap-2 px-2.5 h-8 rounded-full bg-white/[0.06] border border-white/[0.08]">
            <Search className="w-3.5 h-3.5 text-[rgba(235,235,245,0.4)] shrink-0" />
            <input
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Filter these jobs"
              className="flex-1 min-w-0 bg-transparent text-[12.5px] text-[#f5f5f7] placeholder:text-[rgba(235,235,245,0.32)] focus:outline-none"
            />
          </div>
        </div>

        <div className="flex-1 min-h-0 overflow-y-auto custom-scrollbar p-2 space-y-1.5">
          {candidates.length === 0 && (
            <p className="px-2 py-6 text-[12.5px] leading-relaxed text-[rgba(235,235,245,0.45)]">
              Nothing to tailor yet. Search for work on the map, and every result
              lands here with its own CV waiting to be cut.
            </p>
          )}
          {candidates.map((candidate) => {
            const on = candidate.job_id === current?.job_id;
            const running = busy === candidate.job_id;
            return (
              <button
                key={candidate.job_id}
                type="button"
                onClick={() => setSelected(candidate.job_id)}
                className={`w-full text-left px-3 py-2.5 rounded-[14px] transition-colors duration-150 cursor-pointer border ${
                  on
                    ? 'bg-white/[0.09] border-white/[0.14]'
                    : 'bg-transparent border-transparent hover:bg-white/[0.05]'
                }`}
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="min-w-0">
                    <p className="text-[13px] text-[#f5f5f7] truncate">{candidate.title}</p>
                    <p className="text-[11.5px] text-[rgba(235,235,245,0.5)] truncate">
                      {candidate.company}{candidate.location ? ` · ${candidate.location}` : ''}
                    </p>
                  </div>
                  <span className="shrink-0 mt-0.5">
                    {running ? (
                      <Loader2 className="w-3.5 h-3.5 text-[#0a84ff] animate-spin" />
                    ) : candidate.doc ? (
                      <FileText className="w-3.5 h-3.5 text-emerald-400/80" />
                    ) : (
                      <span className="block w-1.5 h-1.5 rounded-full bg-white/20 mt-1" />
                    )}
                  </span>
                </div>
                <div className="mt-1.5 flex items-center gap-2 text-[10.5px]">
                  {candidate.doc ? (
                    <span className="text-[rgba(235,235,245,0.4)]">
                      {candidate.doc.language?.toUpperCase()} · {candidate.doc.bullets_kept} of{' '}
                      {candidate.doc.bullets_available} bullets · {when(candidate.doc)}
                    </span>
                  ) : (
                    <span className="text-[rgba(235,235,245,0.32)]">No documents yet</span>
                  )}
                  {appliedJobIds.has(candidate.job_id) && (
                    <span className="text-emerald-400/70">Applied</span>
                  )}
                </div>
              </button>
            );
          })}
        </div>
      </div>

      {/* THE DOCUMENT. */}
      <div className={`${PANEL} hidden md:flex flex-1 min-w-0 flex-col min-h-0 overflow-hidden`}>
        {!current ? (
          <div className="flex-1 grid place-items-center p-8 text-center">
            <p className="text-[13px] text-[rgba(235,235,245,0.45)] max-w-sm leading-relaxed">
              Pick a job on the left. Its CV is cut from your master, keeping the
              experience that answers the advert and leaving the rest out.
            </p>
          </div>
        ) : (
          <>
            <div className="shrink-0 px-4 pt-3.5 pb-3 border-b border-white/[0.09]">
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <h3 className="text-[15px] text-[#f5f5f7] truncate">{current.title}</h3>
                  <p className="text-[12px] text-[rgba(235,235,245,0.5)] truncate">
                    {current.company}{current.location ? ` · ${current.location}` : ''}
                  </p>
                </div>
                <div className="shrink-0 flex items-center gap-1.5">
                  {current.job && onOpenJob && (
                    <button
                      type="button"
                      onClick={() => onOpenJob(current.job as Job)}
                      className="px-2.5 h-8 rounded-full text-[12px] text-[rgba(235,235,245,0.62)] hover:text-[#f5f5f7] hover:bg-white/[0.08] transition-colors duration-200 cursor-pointer flex items-center gap-1.5"
                      title="Open the listing"
                    >
                      <ExternalLink className="w-3.5 h-3.5" /> Listing
                    </button>
                  )}
                  <button
                    type="button"
                    disabled={!!busy}
                    onClick={() => void run(current, !!doc)}
                    className={`px-3.5 h-8 rounded-full text-[12.5px] font-medium flex items-center gap-1.5 transition-colors duration-200 ${
                      busy
                        ? 'bg-white/[0.08] text-[rgba(235,235,245,0.4)] cursor-wait'
                        : doc
                          ? 'bg-white/[0.1] text-[#f5f5f7] hover:bg-white/[0.16] cursor-pointer'
                          : 'bg-[#0a84ff] text-white hover:bg-[#0a84ff]/90 cursor-pointer'
                    }`}
                  >
                    {busy === current.job_id ? (
                      <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Reading the advert…</>
                    ) : doc ? (
                      <><RefreshCw className="w-3.5 h-3.5" /> Tailor again</>
                    ) : (
                      <><Sparkles className="w-3.5 h-3.5" /> Tailor for this job</>
                    )}
                  </button>
                </div>
              </div>

              {doc && (
                <div className="mt-2.5 flex items-center justify-between gap-1">
                  <div className="flex items-center gap-1 min-w-0">
                    {(['cv', 'letter'] as const).map((which) => (
                      <button
                        key={which}
                        type="button"
                        onClick={() => setKind(which)}
                        className={`px-3 h-7 rounded-full text-[12px] transition-colors duration-200 cursor-pointer ${
                          kind === which
                            ? 'bg-white/[0.12] text-[#f5f5f7]'
                            : 'text-[rgba(235,235,245,0.48)] hover:text-[#f5f5f7] hover:bg-white/[0.06]'
                        }`}
                      >
                        {which === 'cv' ? 'CV' : 'Cover letter'}
                      </button>
                    ))}
                    <span className="ml-2 text-[11px] text-[rgba(235,235,245,0.38)] truncate">
                      {kind === 'cv'
                        ? doc.headline
                        : `${doc.letter_subject || ''}${doc.letter_fallback ? ' · plain version' : ''}`}
                    </span>
                  </div>
                  {previewUrl && (
                    <a
                      href={previewUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="px-2.5 h-7 rounded-full text-[11.5px] font-medium text-[rgba(235,235,245,0.65)] hover:text-[#f5f5f7] hover:bg-white/[0.08] transition-colors duration-200 flex items-center gap-1.5 shrink-0"
                      title="Open document in a new tab to view or print (Ctrl+P)"
                    >
                      <ExternalLink className="w-3 h-3" /> Open / Print
                    </a>
                  )}
                </div>
              )}
            </div>

            {error && (
              <p role="alert" className="mx-4 mt-3 rounded-xl bg-rose-500/12 border border-rose-400/20 px-3 py-2 text-[12px] text-rose-200">
                {error}
              </p>
            )}

            <div className="flex-1 min-h-0 p-3">
              {doc && previewUrl ? (
                <iframe
                  key={`${doc.job_id}-${kind}-${doc.epoch || 0}`}
                  src={previewUrl}
                  title={kind === 'cv' ? 'The tailored CV' : 'The tailored cover letter'}
                  className="w-full h-full rounded-[14px] border border-white/[0.08] bg-white"
                />
              ) : (
                <div className="h-full grid place-items-center text-center px-8">
                  <div className="max-w-md">
                    <p className="text-[13px] leading-relaxed text-[rgba(235,235,245,0.5)]">
                      {busy === current.job_id
                        ? 'Reading the advert against your master CV, choosing what to show, then printing both documents. About twenty seconds.'
                        : 'No documents for this job yet. Tailoring picks from the bullets already in your master — it never writes new ones.'}
                    </p>
                  </div>
                </div>
              )}
            </div>

            {doc && (
              <div className="shrink-0 px-4 py-2.5 border-t border-white/[0.09] flex flex-wrap items-center gap-x-4 gap-y-1 text-[11px] text-[rgba(235,235,245,0.42)]">
                <span>{doc.bullets_kept} of {doc.bullets_available} bullets kept</span>
                {doc.skills_kept?.length ? <span>{doc.skills_kept.length} skills shown</span> : null}
                {reverted.length > 0 && (
                  <span className="text-amber-200/70">
                    {reverted.length} rewrite{reverted.length === 1 ? '' : 's'} refused — your own wording used instead
                  </span>
                )}
                {invented.length > 0 && (
                  <span className="text-amber-200/70" title={invented.join(', ')}>
                    caught: {invented.slice(0, 4).join(', ')}
                  </span>
                )}
                {offLanguage.length > 0 && (
                  <span className="text-amber-200/70">
                    {offLanguage.join(' and ')} came back in the advert&apos;s language — your
                    master&apos;s {doc.language?.toUpperCase()} kept, so the page reads as one document
                  </span>
                )}
                {offVoice.length > 0 && (
                  <span className="text-amber-200/70">
                    written about you rather than by you (&quot;{offVoice[0]}&quot;) — your own wording kept
                  </span>
                )}
                {doc.why && <span className="truncate max-w-[40ch]" title={doc.why}>{doc.why}</span>}
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}
